{% set name = "python-cinderclient" %}
{% set version = "6.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 48f5a0df0983bd06c0c870b728f2952a3fe4b67a4dc0031afaef0536e829d097

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - cinder = cinderclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python
    - setuptools
  run:
    - babel
    - keystoneauth1
    - oslo.i18n
    - oslo.utils
    - pbr
    - prettytable <0.8,>=0.7.1
    - python
    - requests
    - setuptools
    - simplejson
    - six

test:
  imports:
    - cinderclient

about:
  home: https://docs.openstack.org/python-cinderclient/latest/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "OpenStack Block Storage API Client Library"
  doc_url: https://docs.openstack.org/python-cinderclient/latest/
  dev_url: https://opendev.org/openstack/python-cinderclient

extra:
  recipe-maintainers:
    - tschoonj
