{% set name = "python-cinderclient" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff5cd2f28dd7558a7244d4072e472ae5d9a6b180158e26586a6312624cd1ec14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cinder = cinderclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >3
    - setuptools
  run:
    - babel
    - keystoneauth1
    - oslo.i18n
    - oslo.utils
    - pbr
    - prettytable
    - python >3
    - requests
    - setuptools
    - simplejson
    - six

test:
  imports:
    - cinderclient

about:
  home: https://docs.openstack.org/python-cinderclient/latest/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Block Storage API Client Library
  doc_url: https://docs.openstack.org/python-cinderclient/latest/
  dev_url: https://opendev.org/openstack/python-cinderclient

extra:
  recipe-maintainers:
    - tschoonj
